export const projects = [
  {
    id: 'silverbot',
    name: 'SILVERBOT',
    tagline: '75x leverage silver scalping with ML inference',
    accent: '#7B68EE',
    features: [
      'ONNX ML signal prediction',
      'Aster DEX integration',
      'TUI control panel',
      'Real-time PnL tracking',
      'Kill switches + drawdown limits',
    ],
    tech: ['Rust', 'tokio', 'ratatui', 'ONNX Runtime', 'secp256k1'],
    status: 'live',
    orbType: 'icosahedron',
  },
  {
    id: 'liqsnip',
    name: 'LIQSNIP',
    tagline: 'Solana liquidation sniper with atomic flash loans',
    accent: '#00E5FF',
    features: [
      'Flash loan liquidations',
      'Jito MEV bundle protection',
      'WebSocket account monitoring',
      'Redis-backed safety locks',
      'Telegram alerts',
    ],
    tech: ['Rust', 'Solana', 'Redis', 'WebSocket', 'Jito'],
    status: 'live',
    orbType: 'sphere',
  },
  {
    id: 'cdaw',
    name: 'CDAW',
    tagline: 'Professional DAW with modular Eurorack routing',
    accent: '#FF6B00',
    features: [
      'Sub-10ms audio latency',
      'VST3/AU/CLAP hosting',
      'Modular CV routing',
      'Professional DSP effects',
      'Metal shader rendering',
    ],
    tech: ['Swift', 'Xcode', 'Audio Engine', 'Metal', 'CoreAudio'],
    status: 'dev',
    orbType: 'torus',
  },
  {
    id: 'launchpad',
    name: 'BNB LAUNCHPAD',
    tagline: 'pump.fun competitor for Binance Smart Chain',
    accent: '#F0B90B',
    features: [
      'Token factory with bonding curves',
      'PancakeSwap auto-migration',
      'Real-time price charts',
      'Security-audited contracts',
      'Full trading interface',
    ],
    tech: ['Solidity', 'Next.js 14', 'Foundry', 'TypeScript', 'React'],
    status: 'live',
    orbType: 'sphere',
  },
  {
    id: 'codox-terminal',
    name: 'CODOX TERMINAL',
    tagline: 'Bloomberg-style crypto terminal with AI insights',
    accent: '#00FF88',
    features: [
      'Real-time multi-symbol charts',
      'Market heatmap',
      'AI prediction engine',
      'Lunar phase analysis',
      'Live news + sentiment',
    ],
    tech: ['Next.js 14', 'Three.js', 'Framer Motion', 'TypeScript', 'React Query'],
    status: 'live',
    orbType: 'box',
  },
  {
    id: 'codox-token',
    name: 'CODOX TOKEN',
    tagline: 'Solana token with reflection rewards and lottery',
    accent: '#9945FF',
    features: [
      'Reflection rewards (passive income)',
      '25% APY staking',
      'Daily lottery system',
      'Anti-whale protection',
      'Deflationary burn mechanics',
    ],
    tech: ['Rust', 'Solana Program', 'JavaScript', 'Node.js'],
    status: 'live',
    orbType: 'dodecahedron',
  },
];

export const timelineData = [
  { project: 'CODOX TOKEN', color: '#9945FF', note: 'Started with Solana token mechanics' },
  { project: 'LIQSNIP', color: '#00E5FF', note: 'Evolved into MEV and liquidation systems' },
  { project: 'SILVERBOT', color: '#7B68EE', note: 'Refined into precision trading with ML' },
  { project: 'CDAW', color: '#FF6B00', note: 'Applied real-time systems to audio' },
  { project: 'BNB LAUNCHPAD', color: '#F0B90B', note: 'Full-stack DeFi product' },
  { project: 'CODOX TERMINAL', color: '#00FF88', note: 'Unified everything into a single interface' },
];
