export const categories = [
  { id: 'bots', label: 'TRADING BOTS', color: '#00E5FF' },
  { id: 'apps', label: 'APPS', color: '#FF6B00' },
  { id: 'web', label: 'WEB PLATFORMS', color: '#00FF88' },
  { id: 'games', label: 'GAMES', color: '#FF3366' },
  { id: 'ai', label: 'AI / ML', color: '#9945FF' },
  { id: 'audio', label: 'AUDIO', color: '#F0B90B' },
];

export const projects = [
  // ─── TRADING BOTS ───
  {
    id: 'silverbot',
    name: 'SILVERBOT',
    category: 'bots',
    tagline: 'Autonomous perpetual futures trading system with hybrid genetic algorithm + reinforcement learning',
    accent: '#7B68EE',
    features: [
      '66K lines of Rust — hybrid GA + RL autonomous learning engine',
      '6 ensemble strategies with regime detection (trending/ranging/choppy)',
      'ONNX neural network inference — 64-feature signal prediction',
      'Smart execution engine — fill probability modeling, dynamic order chase',
      'Synthwave TUI dashboard with real-time PnL, Sharpe, and confidence meters',
    ],
    tech: ['Rust', 'tokio', 'ratatui', 'ONNX Runtime', 'secp256k1', 'polars'],
    status: 'live',
    orbType: 'icosahedron',
    description: 'Production trading bot for AsterDex. Trades Silver at 75x and BTC at 100x leverage. Features tournament-based strategy evolution with Elo ratings, walk-forward backtesting, and kill switch safety systems. 59 tests across 4 suites. Audited with 5/7 execution invariants passing.',
  },
  {
    id: 'liqsnip',
    name: 'LIQSNIP',
    category: 'bots',
    tagline: 'Solana liquidation sniper with flash loans, MEV bundles, and multi-protocol monitoring',
    accent: '#00E5FF',
    features: [
      '29K lines of Rust — monitors Kamino, Drift, and Solend simultaneously',
      'Flash loan liquidations via Solend, Port Finance, and Jupiter FLM',
      'Jito MEV bundle submission with transaction obfuscation and tip optimization',
      'Multi-RPC failover with circuit breaker pattern and health tracking',
      'Anti-rug detection engine with risk scoring and token safety analysis',
    ],
    tech: ['Rust', 'Solana', 'Redis', 'Jito SDK', 'Pyth Oracle', 'WebSocket'],
    status: 'live',
    orbType: 'sphere',
    description: 'Production Solana liquidation bot. Detects underwater positions across 3 lending protocols in real-time via Helius WebSocket. Executes atomic flash loan liquidations through Jito bundles with MEV protection. Includes competitor analysis, parallel scanning, and Telegram alerts. Full test suite with integration tests.',
  },
  {
    id: 'asterbot',
    name: 'ASTERBOT',
    category: 'bots',
    tagline: 'AsterDex perpetual futures bot with backtesting engine and AI-driven signal analysis',
    accent: '#4488FF',
    features: [
      'Full backtesting framework with walk-forward validation',
      'AI agent integration via OpenRouter and DeepSeek for market analysis',
      'Aggressive take-profit optimization with dynamic trailing stops',
      'TUI dashboard with real-time position tracking',
      'Comprehensive audit reports and deployment documentation',
    ],
    tech: ['Rust', 'tokio', 'ethers-rs', 'ratatui', 'linfa', 'ta'],
    status: 'live',
    orbType: 'icosahedron',
    description: 'Predecessor to Silverbot. Full perpetual futures trading system for AsterDex with technical analysis indicators, backtesting, and AI-assisted signal generation. Production-tested with multiple audit cycles.',
  },
  {
    id: 'numberbot',
    name: 'NUMBERBOT',
    category: 'bots',
    tagline: 'Numerology-driven crypto trading bot with Telegram integration and signal persistence',
    accent: '#E040FB',
    features: [
      'Custom numerology signal generation algorithm for trade entry/exit',
      'SQLite-backed signal storage with historical analysis',
      'Backtesting framework for validating numerology signals',
      'Telegram bot interface for real-time alerts and control',
      'TUI dashboard with signal confidence visualization',
    ],
    tech: ['Rust', 'tokio', 'ethers-rs', 'teloxide', 'SQLite', 'ratatui'],
    status: 'live',
    orbType: 'dodecahedron',
    description: 'Experimental trading bot combining numerological signal generation with crypto market execution. Features full backtesting, Telegram notifications, and persistent signal database.',
  },

  // ─── APPS ───
  {
    id: 'cdaw',
    name: 'CDAW',
    category: 'apps',
    tagline: 'FL Studio-inspired digital audio workstation with Metal rendering and modular synthesis',
    accent: '#FF6B00',
    features: [
      '50K lines of Swift — 78 source files with full audio production pipeline',
      '5 synthesizers: 3xOsc, Sytrus FM, Harmless, Sakura, Sawer',
      '8-channel step sequencer with 4 DSP effects (Reverb, Delay, EQ, Compressor)',
      'Comprehensive MIDI engine with MPE support and sample-accurate timing',
      'Early 2000s FL Studio aesthetic with Metal-accelerated shader rendering',
    ],
    tech: ['Swift', 'SwiftUI', 'AVFoundation', 'Metal', 'CoreAudio', 'CoreMIDI'],
    status: 'dev',
    orbType: 'torus',
    description: 'Full digital audio workstation for macOS. Working step sequencer, piano roll, mixer with VU meters, and browser panel. 5 synthesizers and 4 effects processors. Multi-mode recording (MIDI, audio, overdub, punch, loop, comping). Thread pool for real-time audio processing. C++ backend framework designed for VST3/AU/CLAP hosting.',
  },
  {
    id: 'hlcarplay',
    name: 'HL CARPLAY',
    category: 'apps',
    tagline: 'Hyperliquid perpetual futures dashboard for Apple CarPlay',
    accent: '#FF3366',
    features: [
      'Native SwiftUI interface with CarPlay extension',
      'Real-time position and PnL tracking from Hyperliquid',
      'Price charts rendered natively on CarPlay display',
      'Settings panel with configurable alerts and thresholds',
      'Multi-target build: standalone iOS app + CarPlay extension',
    ],
    tech: ['Swift', 'SwiftUI', 'CarPlay Framework', 'URLSession', 'Charts'],
    status: 'dev',
    orbType: 'box',
    description: 'iOS app that brings Hyperliquid trading data to your car dashboard via Apple CarPlay. View positions, charts, and PnL while driving. Full data model integration with Hyperliquid API.',
  },

  // ─── WEB PLATFORMS ───
  {
    id: 'codox-terminal',
    name: 'CODOX TERMINAL',
    category: 'web',
    tagline: 'Bloomberg-style crypto terminal with generative ambient music and 3D immersive scenes',
    accent: '#00FF88',
    features: [
      '25K lines of TypeScript — 89 source files, 48 React components',
      '19 analytical widgets: candlestick charts, heatmaps, whale tracking, liquidation maps',
      'Generative ambient music engine with granular synthesis, ADSR envelopes, and tape effects',
      '3D scenes with React Three Fiber — audio-reactive particles, frequency visualizers',
      'Real-time data from Binance WebSocket, CoinGecko, Helius, and OpenRouter AI',
    ],
    tech: ['Next.js 14', 'Three.js', 'R3F', 'Web Audio API', 'TypeScript', 'Zustand'],
    status: 'live',
    orbType: 'box',
    description: 'Comprehensive crypto terminal combining Bloomberg-style financial analytics with an immersive audio-visual experience. 25 terminal commands, multi-timeframe AI signal generation, cross-exchange arbitrage detection, and a full generative synthesizer with drone, melody, and texture layers.',
  },
  {
    id: 'launchpad',
    name: 'BNB LAUNCHPAD',
    category: 'web',
    tagline: 'Pump.fun-style memecoin factory for BNB Chain with bonding curves and PancakeSwap migration',
    accent: '#F0B90B',
    features: [
      '11 Solidity contracts with Forge test suites and OpenZeppelin security',
      'Bonding curve market — linear, exponential, and sigmoid pricing models',
      'Auto-migration to PancakeSwap V2 at 10 BNB threshold with LP locking',
      'Anti-bot guard with cooldowns, blacklisting, and max wallet limits',
      'Full Next.js 14 frontend with wagmi wallet integration and Recharts visualization',
    ],
    tech: ['Solidity', 'Foundry', 'Next.js 14', 'wagmi', 'TypeScript', 'The Graph'],
    status: 'dev',
    orbType: 'sphere',
    description: 'Decentralized memecoin launchpad for BNB Chain. One-click token deployment, bonding curve trading, and automatic PancakeSwap liquidity migration. Anti-rug features: ownerless tokens, LP locks (30-365 days), max transaction limits. Subgraph indexing for real-time data.',
  },
  {
    id: 'codox-token',
    name: 'CODOX TOKEN',
    category: 'web',
    tagline: 'Solana token program with reflection rewards, staking yields, and on-chain lottery',
    accent: '#9945FF',
    features: [
      'Custom Solana program in Rust with 5% tax structure (reflections + burn + lottery)',
      '25% APY staking with automatic reward distribution',
      'Daily lottery system with verifiable on-chain randomness',
      'Anti-whale protection with max transaction and wallet limits',
      'Interactive web frontend with music integration and physics interactions',
    ],
    tech: ['Rust', 'Solana Program', 'SPL Token', 'Borsh', 'JavaScript', 'Node.js'],
    status: 'live',
    orbType: 'dodecahedron',
    description: 'Full Solana token with on-chain tax mechanics, reflection rewards for holders, staking pools, and a lottery system. Interactive web frontend with Easter eggs, audio analysis, and gesture recognition.',
  },

  // ─── GAMES ───
  {
    id: 'horror-engine',
    name: 'SILENT HORROR',
    category: 'games',
    tagline: 'Custom C++ horror game engine with ECS architecture, OpenGL rendering, and 3D spatial audio',
    accent: '#FF3366',
    features: [
      'Entity Component System architecture with custom memory management',
      'OpenGL rendering pipeline with fog, shadow mapping, and post-processing',
      'OpenAL 3D spatial audio for positional horror sound design',
      'Asset pipeline with Assimp model loading (FBX, OBJ, GLTF)',
      '30+ architecture docs covering animation, networking, and procedural generation',
    ],
    tech: ['C++', 'CMake', 'OpenGL', 'GLFW', 'Assimp', 'OpenAL'],
    status: 'dev',
    orbType: 'icosahedron',
    description: 'Custom horror game engine built from scratch in C++. Professional ECS architecture with components for rendering, physics, audio, and AI. OpenGL pipeline with atmospheric effects. Designed for psychological horror with procedural level generation and adaptive AI.',
  },
  {
    id: 'mii-creator',
    name: 'MII CREATOR',
    category: 'games',
    tagline: '3D character creator inspired by Nintendo Mii with Three.js and physics interactions',
    accent: '#FFD700',
    features: [
      'Three.js 3D character modeling with customizable features',
      'GSAP-powered animations and smooth transitions',
      'Physics interactions for dynamic character posing',
      'Vite-powered dev environment with hot reload',
      'Web-based — runs entirely in the browser',
    ],
    tech: ['JavaScript', 'Three.js', 'GSAP', 'Vite', 'Node.js'],
    status: 'dev',
    orbType: 'sphere',
    description: 'Browser-based 3D character creation tool inspired by Nintendo Mii. Create and customize characters with real-time 3D preview and physics-based interactions.',
  },

  // ─── AI / ML ───
  {
    id: 'cortex-forge',
    name: 'CORTEX FORGE',
    category: 'ai',
    tagline: 'Rust agent workspace with Telegram bot integration and SQLite-backed trading intelligence',
    accent: '#00BCD4',
    features: [
      'Multi-crate Rust workspace: cortex-common, cortex-daemon, cortex-trading',
      'Telegram bot interface via teloxide for remote agent control',
      'SQLite persistence layer for trading data and agent state',
      'Async architecture with tokio for concurrent task management',
      '75 tests passing across the workspace',
    ],
    tech: ['Rust', 'tokio', 'teloxide', 'rusqlite', 'serde', 'SQLite'],
    status: 'dev',
    orbType: 'box',
    description: 'Foundation for an AI agent ecosystem. Three integrated Rust crates providing shared utilities, a background daemon with Telegram integration, and trading-specific logic. Designed as the backbone for autonomous trading agents.',
  },
  {
    id: 'neural-gen',
    name: 'NEURAL GEN',
    category: 'ai',
    tagline: 'StyleGAN2 implementation in PyTorch for bizarre procedural image generation',
    accent: '#E91E63',
    features: [
      'Custom StyleGAN2 architecture with style mixing and mapping network',
      'PyTorch Lightning training framework with W&B experiment tracking',
      'Gradient penalty regularization for stable training',
      '256x256 image generation with progressive growing',
      'Pre-trained model checkpoints included',
    ],
    tech: ['Python', 'PyTorch', 'PyTorch Lightning', 'Weights & Biases', 'NumPy'],
    status: 'prototype',
    orbType: 'sphere',
    description: 'Custom StyleGAN2 implementation for generating surreal, procedural images. Full training pipeline with experiment tracking, style mixing, and pre-trained checkpoints.',
  },

  // ─── AUDIO ───
  {
    id: 'tapsynth',
    name: 'TAPSYNTH',
    category: 'audio',
    tagline: 'JUCE-based synthesizer VST plugin with custom DSP and preset management',
    accent: '#F0B90B',
    features: [
      'JUCE C++ framework for cross-platform audio plugin development',
      'Custom DSP signal processing pipeline',
      'VST3/AU plugin format support',
      'Preset management and parameter automation',
      'Real-time waveform visualization',
    ],
    tech: ['C++', 'JUCE', 'VST3', 'AU', 'DSP'],
    status: 'prototype',
    orbType: 'torus',
    description: 'Synthesizer plugin built with the JUCE framework. Cross-platform VST3/AU support with custom digital signal processing.',
  },
];

export const timelineData = [
  { project: 'CODOX TOKEN', color: '#9945FF', note: 'Started with Solana token mechanics and on-chain programs' },
  { project: 'LIQSNIP', color: '#00E5FF', note: 'Evolved into MEV, flash loans, and liquidation systems' },
  { project: 'ASTERBOT', color: '#4488FF', note: 'First perpetual futures bot — backtesting and execution' },
  { project: 'SILVERBOT', color: '#7B68EE', note: 'Refined into autonomous ML trading with genetic algorithms' },
  { project: 'CDAW', color: '#FF6B00', note: 'Applied real-time systems knowledge to audio production' },
  { project: 'BNB LAUNCHPAD', color: '#F0B90B', note: 'Full-stack DeFi product with bonding curves' },
  { project: 'SILENT HORROR', color: '#FF3366', note: 'Built a game engine from scratch in C++' },
  { project: 'CORTEX FORGE', color: '#00BCD4', note: 'Designing autonomous agent infrastructure' },
  { project: 'CODOX TERMINAL', color: '#00FF88', note: 'Unified everything into a single immersive interface' },
];
